services:
  rabbitmq:
    image: rabbitmq:4.0.9-management
    restart: always
    volumes_from:
      - rabbitmq-datavolume
    ports:
      - 5672:5672/tcp
      - 15672:15672/tcp
    environment:
      - RABBITMQ_ERLANG_COOKIE=defaultcookiepleasechange
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  rabbitmq-datavolume:
    volumes:
      - /etc/rabbitmq
      - /opt/rancher/bin
    entrypoint: /bin/true
    image: rabbitmq:4.0.9-management
